# Generated by Django 5.0.7 on 2024-07-12 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='nomi')),
                ('video', models.FileField(upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MOV', 'AVI', 'WMV'])])),
            ],
            options={
                'unique_together': {('title',)},
            },
        ),
    ]
